services:
  app:
    build:
      context: .
      args:
        - SUPABASE_URL=http://${POSTGRES_HOST}:${SUPABASE_API_PORT}
        - SUPABASE_KEY=${SUPABASE_KEY}
    environment:
      - SUPABASE_DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - NODE_ENV=production
    ports:
      - "${LMIX_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"