services:
  app:
    build:
      context: .
      args:
        - SUPABASE_URL=http://host.docker.internal:${SUPABASE_API_PORT}
        - SUPABASE_KEY=${SUPABASE_KEY}
    environment:
      - SUPABASE_DB_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
      - NODE_ENV=production
    ports:
      - "${LMIX_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"